# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'GlobalLogic' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GlobalLogic
  pod 'PureLayout'
  pod 'SDWebImage'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Alamofire'
  pod 'lottie-ios'
  target 'GlobalLogicTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GlobalLogicUITests' do
    # Pods for testing
  end

end
